patient_id_col: patientid

patient:
  dob: 
    code: "DOB"
    timestamp: col(dateofbirth)
  gender:
    code: ["GENDER", "col(gender)"]
    timestamp: null

admissions:
  icu_admission:
    code:
      - "ICU_ADMISSION"
      - col(location)
      - col(urgency)
      - col(origin)
      - col(specialty)
    timestamp: col(admittedattimestamp)
  icu_discharge:
    code: 
      - "ICU_DISCHARGE"
      - col(destination)
    timestamp: col(dischargedattimestamp)
  weight:
    code:
      - "WEIGHT_AT_ADMISSION"
      - col(weightsource)
      - col(weightgroup)
    timestamp: col(admittedattimestamp)
  height: 
    code:
      - "HEIGHT_AT_ADMISSION"
      - col(heightsource)
      - col(heightgroup)
    timestamp: col(admittedattimestamp)

numericitems:
  event:
    code:
      - MEASURE
      - col(item)
      - col(unit)
    timestamp: col(measuredattimestamp)
    numerical_value: value

listitems:
  event:
    code:
      - MEASURE
      - col(item)
      - col(islabresult)
      - col(value)
    timestamp: col(measuredattimestamp)
  
freetextitems:
  event:
    code:
      - MEASURE
      - col(item)
      - col(islabresult)
    timestamp: col(measuredattimestamp)
    text_value: value

procedureorderitems:
  event: 
    code:
      - PROCEDURE
      - col(ordercategoryname)
      - col(item)
    timestamp: col(registeredattimestamp)

processitems:
  start: 
    code:
      - PROCESS
      - START
      - col(item)
    timestamp: col(starttimestamp)
  end:
    code: 
      - PROCESS
      - END
      - col(item)
    timestamp: col(stoptimestamp)

drugitems: 
  start: 
    code:
      - DRUG
      - START
      - col(ordercategory)
      - col(item)
      - col(action)
    timestamp: col(starttimestamp)
  rate: 
    code:
      - DRUG
      - RATE
      - col(ordercategory)
      - col(item)
      - col(rateunit)
    timestamp: col(starttimestamp)
    numerical_value: col(rate)
  dose: 
    code:
      - DRUG
      - DOSE
      - col(ordercategory)
      - col(item)
      - col(doseunit)
    timestamp: col(starttimestamp)
    numerical_value: col(dose)
  end:
    code:
      - DRUG
      - END
      - col(ordercategory)
      - col(item)
    timestamp: col(stoptimestamp)
